version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - AMAZONDEX_ENTRADAS_DIR=${AMAZONDEX_ENTRADAS_DIR}
    volumes:
      - ./src/main/resources/schema.sql:/app/schema.sql
    working_dir: /app
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}